import json
from openai import AsyncOpenAI
from app.core.config import get_settings
from app.utils.errors import LLMError


class AgentService:
    def __init__(self):
        self.settings = get_settings()

    def _get_client(self) -> AsyncOpenAI:
        if not self.settings.openai_api_key:
            raise LLMError("OpenAI API key is not configured")
        return AsyncOpenAI(api_key=self.settings.openai_api_key)

    async def explain_recommendations(
        self, candidates: list[dict], taste_profile: dict | None
    ) -> dict:
        client = self._get_client()

        taste_summary = ""
        if taste_profile:
            top_artists = [a["name"] for a in taste_profile.get("topArtists", [])[:5]]
            top_genres = [g["name"] for g in taste_profile.get("topGenres", [])[:5]]
            detected = taste_profile.get("detectedTaste", [])
            moods = taste_profile.get("moodTags", [])
            taste_summary = (
                f"Top Artists: {', '.join(top_artists)}\n"
                f"Top Genres: {', '.join(top_genres)}\n"
                f"Detected Taste: {', '.join(detected)}\n"
                f"Mood Tags: {', '.join(moods)}"
            )

        candidates_text = "\n".join(
            f"- {c['title']} by {c['artist']} (Genre: {c['genre']}, Score: {c['score']:.1f}, Path: {c['graphPath']})"
            for c in candidates[:10]
        )

        prompt = f"""You are a music recommendation assistant for VibeGraph, a graph-based music recommendation system.

User Taste Profile:
{taste_summary if taste_summary else "No taste profile available."}

Recommended Track Candidates (generated by Neo4j graph traversal):
{candidates_text}

For each track, write a concise recommendation reason (1-2 sentences) that:
1. References the graph path that led to this recommendation
2. Mentions specific genre, mood, or artist connections
3. Explains why it fits the user's taste

Also generate a creative playlist name that reflects the user's taste.

Respond ONLY with valid JSON in this exact format:
{{
  "playlistName": "Creative playlist name here",
  "explanation": "Brief overall explanation of the recommendation strategy",
  "tracks": [
    {{
      "id": "track_id",
      "title": "Track Title",
      "artist": "Artist Name",
      "genre": "Genre",
      "score": 0.0,
      "graphPath": "path string",
      "reason": "Personalized recommendation reason"
    }}
  ]
}}"""

        try:
            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                response_format={"type": "json_object"},
            )
            content = response.choices[0].message.content
            result = json.loads(content)

            # Merge LLM reasons back into candidates
            reason_map = {t["id"]: t.get("reason", "") for t in result.get("tracks", [])}
            enriched = []
            for c in candidates:
                enriched.append({**c, "reason": reason_map.get(c["id"], c.get("reason", ""))})

            return {
                "playlistName": result.get("playlistName", "VibeGraph Mix"),
                "explanation": result.get("explanation", ""),
                "tracks": enriched,
            }
        except json.JSONDecodeError as e:
            raise LLMError(f"Failed to parse LLM response as JSON: {str(e)}")
        except Exception as e:
            raise LLMError(f"LLM API call failed: {str(e)}")
